name: Deploy Config Server
on: [push]
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: chmod gradlew
        run: chmod +x gradlew  # Важно!
      
      - name: Build JAR
        run: ./gradlew :config-server:build

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and Push Image
        run: |
          docker build -t your-dockerhub/config-server:latest -f config-server/Dockerfile .
          docker push your-dockerhub/config-server:latest
